### ISSUE TITLE
use_transactional_fixtures not defined in Capybara::Rails::TestCase

### ISSUE THREAD

**Issue by jimmykarily** [minitest/minitest-rails#161]
I used to have this in my minitest_helper, as part of my DatabaseCleaner setup.

```
class Capybara::Rails::TestCase
  # Disable transactions for tests
  self.use_transactional_fixtures = false
end
```

After upgrading from minitest-rails 0.5.2 to 2.1.1 (part of the rails 4.0.10 to 4.1.1 upgrade), this no longer works. It fails with error:

```
NoMethodError: undefined method `use_transactional_fixtures=' for Capybara::Rails::TestCase:Class
```

I digged a little on how this worked on the old versions. This gem used to include ActiveRecord::TestFixtures module (but was removed [here](http://www.github.com/blowmage/minitest-rails/commit/537cd56e93caa43447d8b1c3e162a64026baa683#diff-064ef6d0c3847857f83b5a3bc7bccd5fL95)).  This module defined a class_attribute :use_transactional_fixtures [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/fixtures.rb#L835) (still does). With some magic from ActiveSupport [here](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/class/attribute.rb#L86) this attribute was available in our test class to override. 

Is there a way to disable the transactional_fixtures now?
