### ISSUE TITLE
NoMethodError: undefined method `assert_' for nil:NilClass

### ISSUE THREAD

**Issue by mariochavez** [minitest/minitest-rails#137]
Hi,

I tried to have minitest-rails working with Rails 4.1.rc1 without caring support for Rails 4.0 or below - it's more like a butcher work - but I hit a road block and I don't know how to solve it. Maybe some one here can help me to figure out the issue.

This is my repo https://github.com/mariochavez/minitest-rails on where I have 4 failing tests:

```
1) Error:
TestActionControllerExpectations#test_must_dom_equal:
NoMethodError: undefined method `assert_dom_equal' for nil:NilClass
  test/rails/action_controller/test_expectations.rb:34:in `test_must_dom_equal'

2) Error:
TestActionControllerExpectations#test_routing_expectations:
NoMethodError: undefined method `assert_generates' for nil:NilClass
  test/rails/action_controller/test_expectations.rb:24:in `test_routing_expectations'

3) Error:
TestActiveSupportExpectations#test_must_change:
NoMethodError: undefined method `assert_difference' for nil:NilClass
  test/rails/active_support/test_expectations.rb:9:in `test_must_change'

4) Error:
TestActiveSupportExpectations#test_wont_change:
NoMethodError: undefined method `refute_difference' for nil:NilClass
  test/rails/active_support/test_expectations.rb:19:in `test_wont_change'
```
